
services:
  app:
    build: .
    environment:
      - NYT_API_KEY=${NYT_API_KEY}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      - START_DATE=${START_DATE}
      - END_DATE=${END_DATE}
      - BACKFILL=${BACKFILL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
    volumes:
      - ./data:/app/data
      - ./sql_results:/app/sql_results
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgresdb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
